cmake_minimum_required(VERSION 3.20)
project(status LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
add_library(status status.cpp)
add_executable(status_cli main.cpp)
target_include_directories(status PUBLIC include)
find_package(OpenSSL REQUIRED)
add_test(NAME status_test COMMAND status_cli)
install(TARGETS status status_cli)
