using EffortHours.Change;
using EffortHours.Contracts;
using EffortHours.Contracts.V1;
using EffortHours.Reporting;

namespace EffortHours.Tests;

public sealed class ChangeEstimatorTests
{
    private const string ProjectFile =
        "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup>" +
        "<TargetFramework>net10.0</TargetFramework>" +
        "<ImplicitUsings>enable</ImplicitUsings>" +
        "</PropertyGroup></Project>";

    [Fact]
    public async Task FormattingOnlyChangeHasZeroEffort()
    {
        ChangeState before = State(
            ("Demo.csproj", ProjectFile),
            ("Widget.cs", "namespace Demo;\npublic sealed class Widget { public int Value => 1; }\n"));
        ChangeState after = State(
            ("Demo.csproj", ProjectFile),
            ("Widget.cs", "namespace Demo;\n\npublic sealed class Widget\n{\n    public int Value => 1;\n}\n"));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathClassification.FormattingOnly, path.Classification);
        Assert.False(path.Represented);
        Assert.Equal(0m, report.TotalEffort.Expected);
        Assert.Empty(report.WorkItems);
    }

    [Fact]
    public async Task WhitespaceInsideAStringIsRepresentedAsMeaningfulChange()
    {
        ChangeState before = State(
            ("Demo.csproj", ProjectFile),
            ("Message.cs", "namespace Demo; public static class Message { public const string Value = \"a b\"; }\n"));
        ChangeState after = State(
            ("Demo.csproj", ProjectFile),
            ("Message.cs", "namespace Demo; public static class Message { public const string Value = \"ab\"; }\n"));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathClassification.Represented, path.Classification);
        Assert.True(path.Represented);
        Assert.True(report.TotalEffort.Expected > 0m);
    }

    [Fact]
    public async Task ExactMoveHasZeroEffort()
    {
        const string source = "namespace Demo; public sealed class Widget { }\n";
        ChangeState before = State(("Demo.csproj", ProjectFile), ("Old/Widget.cs", source));
        ChangeState after = State(("Demo.csproj", ProjectFile), ("New/Widget.cs", source));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathStatus.Moved, path.Status);
        Assert.Equal("Old/Widget.cs", path.PreviousPath);
        Assert.Equal(ChangePathClassification.ExactMove, path.Classification);
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Fact]
    public async Task GeneratedLockAndExactCopyBodiesAreExcluded()
    {
        const string source = "namespace Demo; public sealed class Original { }\n";
        ChangeState before = State(("Demo.csproj", ProjectFile), ("Original.cs", source));
        ChangeState after = State(
            ("Demo.csproj", ProjectFile),
            ("Original.cs", source),
            ("Copy.cs", source),
            ("Generated.g.cs", "// <auto-generated />\nnamespace Demo; internal class Generated { }\n"),
            ("package-lock.json", "{\"lockfileVersion\":3,\"packages\":{}}"));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        Assert.Equal(3, report.Evidence.Paths.Count);
        Assert.Contains(report.Evidence.Paths, path =>
            path.Path == "Copy.cs" && path.Classification == ChangePathClassification.ExactDuplicate);
        Assert.Contains(report.Evidence.Paths, path =>
            path.Path == "Generated.g.cs" && path.Classification == ChangePathClassification.Generated);
        Assert.Contains(report.Evidence.Paths, path =>
            path.Path == "package-lock.json" && path.Classification == ChangePathClassification.Lockfile);
        Assert.All(report.Evidence.Paths, path => Assert.False(path.Represented));
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Fact]
    public async Task MeaningfulImplementationTestsAndDocumentationAffectTheirCategories()
    {
        ChangeState before = State(("Demo.csproj", ProjectFile));
        ChangeState after = State(
            ("Demo.csproj", ProjectFile),
            ("Calculator.cs", "namespace Demo; public static class Calculator { public static int Add(int a, int b) => a + b; }\n"),
            ("tests/Demo.Tests.csproj", ProjectFile),
            ("tests/CalculatorTests.cs", "namespace Demo.Tests; public sealed class CalculatorTests { [Fact] public void Adds() { Assert.Equal(3, Calculator.Add(1, 2)); } }\n"),
            ("README.md", "# Demo\n\nCall `Calculator.Add` to add two integers.\n"));

        ChangeEstimateReport report = await EstimateAsync(before, after);
        EffortCategory[] categories = [.. report.Categories.Select(category => category.Category)];

        Assert.True(report.TotalEffort.Expected > 0m);
        Assert.Contains(EffortCategory.ProductionImplementation, categories);
        Assert.Contains(EffortCategory.Documentation, categories);
        Assert.Contains(categories, category => category is
            EffortCategory.UnitTesting or
            EffortCategory.IntegrationContractAndComponentTesting or
            EffortCategory.EndToEndAndUiTesting);
        Assert.All(report.WorkItems, item =>
        {
            Assert.InRange(item.Hours.Expected, 0.01m, 8m);
            Assert.NotEmpty(item.EvidenceIds);
        });
    }

    [Fact]
    public async Task DeletionIsPositiveBoundedWorkRatherThanNegativeEffort()
    {
        ChangeState before = State(
            ("Demo.csproj", ProjectFile),
            ("Obsolete.cs", "namespace Demo; public sealed class Obsolete { public int Value => 1; }\n"));
        ChangeState after = State(("Demo.csproj", ProjectFile));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathStatus.Removed, path.Status);
        Assert.True(path.Represented);
        Assert.True(report.TotalEffort.Expected > 0m);
        Assert.All(report.WorkItems, item => Assert.True(item.Hours.Expected > 0m));
    }

    [Fact]
    public async Task DeterministicReportAndExplanationPreserveLineage()
    {
        ChangeState before = State(("Demo.csproj", ProjectFile));
        ChangeState after = State(
            ("Demo.csproj", ProjectFile),
            ("Widget.cs", "namespace Demo; public sealed class Widget { }\n"));

        ChangeEstimateReport first = await EstimateAsync(before, after);
        ChangeEstimateReport second = await EstimateAsync(before, after);
        string firstJson = new ChangeEstimateJsonRenderer().Render(first);
        string secondJson = new ChangeEstimateJsonRenderer().Render(second);
        string markdown = ChangeEstimateMarkdownRenderer.Render(first);
        SchemaValidationResult evidenceSchema = ContractSchemaValidator.Validate(
            SchemaNames.ChangeEvidence,
            ContractJson.Serialize(first.Evidence));

        Assert.Equal(firstJson, secondJson);
        Assert.Contains("Normalized Change EHE", markdown, StringComparison.Ordinal);
        Assert.True(evidenceSchema.IsValid, string.Join(Environment.NewLine, evidenceSchema.Errors));
        WorkItem item = Assert.Single(
            first.WorkItems,
            candidate => candidate.Category == EffortCategory.ProductionImplementation);
        ChangeEstimateExplanation explanation = ChangeEstimateExplainer.Explain(first, item.Id);
        Assert.Equal(item.Id, explanation.RequestedId);
        Assert.NotEmpty(explanation.Evidence);
        Assert.Empty(explanation.UnresolvedEvidenceIds);
        _ = new ChangeEstimateExplanationJsonRenderer().Render(explanation);
    }

    [Fact]
    public async Task RangeReconciliationAllocatesExactlyAndRemovesRevertedWork()
    {
        ChangeState initial = State(("Demo.csproj", ProjectFile));
        ChangeState intermediate = State(
            ("Demo.csproj", ProjectFile),
            ("Temporary.cs", "namespace Demo; public sealed class Temporary { }\n"));
        ChangeState final = State(("Demo.csproj", ProjectFile));
        ChangeComponentInput[] components =
        [
            Component("commit-one", initial, intermediate),
            Component("commit-two", intermediate, final),
        ];

        ChangeEstimateReport report = await EstimateRangeAsync(initial, final, components);

        Assert.Equal(0m, report.TotalEffort.Expected);
        Assert.True(report.Reconciliation.IsolatedComponentSum.Expected > 0m);
        Assert.Equal(
            report.TotalEffort.Expected,
            report.Reconciliation.Components.Sum(component => component.AllocatedExpectedHours));
        Assert.Equal(
            report.Reconciliation.ExpectedDifferenceHours,
            report.Reconciliation.Adjustments.Sum(adjustment => adjustment.EffortDelta.Expected));
        Assert.Contains(report.Reconciliation.Adjustments, adjustment =>
            adjustment.Kind == ChangeAdjustmentKind.Revert);
    }

    [Fact]
    public async Task DisjointNoReworkRangeIsAdditiveWithinDeclaredTolerance()
    {
        ChangeState initial = State(("Demo.csproj", ProjectFile));
        ChangeState first = State(
            ("Demo.csproj", ProjectFile),
            ("Alpha.cs", "namespace Demo; public sealed class Alpha { public int Value => 1; }\n"));
        ChangeState final = State(
            ("Demo.csproj", ProjectFile),
            ("Alpha.cs", "namespace Demo; public sealed class Alpha { public int Value => 1; }\n"),
            ("Beta.cs", "namespace Demo; public sealed class Beta { public int Value => 2; }\n"));

        ChangeEstimateReport report = await EstimateRangeAsync(
            initial,
            final,
            [Component("commit-one", initial, first), Component("commit-two", first, final)]);

        Assert.InRange(
            Math.Abs(report.Reconciliation.ExpectedDifferenceHours),
            0m,
            report.Reconciliation.AdditivityToleranceHours);
        Assert.Equal("within-no-rework-tolerance", report.Reconciliation.Assessment);
        Assert.Equal(
            report.TotalEffort.Expected,
            report.Reconciliation.Components.Sum(component => component.AllocatedExpectedHours));
    }

    [Fact]
    public async Task RepeatedPathEditsAreNamedAsOverlapInsteadOfInflatingFinalEffort()
    {
        ChangeState initial = State(
            ("Demo.csproj", ProjectFile),
            ("Counter.cs", "namespace Demo; public sealed class Counter { public int Value => 1; }\n"));
        ChangeState first = State(
            ("Demo.csproj", ProjectFile),
            ("Counter.cs", "namespace Demo; public sealed class Counter { public int Value => 2; }\n"));
        ChangeState final = State(
            ("Demo.csproj", ProjectFile),
            ("Counter.cs", "namespace Demo; public sealed class Counter { public int Value => 3; }\n"));

        ChangeEstimateReport report = await EstimateRangeAsync(
            initial,
            final,
            [Component("commit-one", initial, first), Component("commit-two", first, final)]);

        Assert.True(report.Reconciliation.IsolatedComponentSum.Expected > report.TotalEffort.Expected);
        Assert.Contains(report.Reconciliation.Adjustments, adjustment =>
            adjustment.Kind == ChangeAdjustmentKind.Overlap);
        Assert.Equal(
            report.Reconciliation.ExpectedDifferenceHours,
            report.Reconciliation.Adjustments.Sum(adjustment => adjustment.EffortDelta.Expected));
    }

    private static async Task<ChangeEstimateReport> EstimateAsync(
        ChangeState before,
        ChangeState after) => await new ChangeEstimator().EstimateAsync(
            Input(ChangeSelectionKind.BaseHead, before, after),
            EstimationProfile.Implementation);

    private static async Task<ChangeEstimateReport> EstimateRangeAsync(
        ChangeState before,
        ChangeState after,
        IReadOnlyList<ChangeComponentInput> components) => await new ChangeEstimator().EstimateAsync(
            Input(ChangeSelectionKind.Range, before, after, components),
            EstimationProfile.Implementation);

    private static ChangeEstimateInput Input(
        ChangeSelectionKind kind,
        ChangeState before,
        ChangeState after,
        IReadOnlyList<ChangeComponentInput>? components = null) => new()
        {
            RepositoryName = "in-memory-change",
            Selection = new ChangeSelection
            {
                Kind = kind,
                Base = Reference("base", before.ObjectId),
                Head = Reference("head", after.ObjectId),
                Range = kind == ChangeSelectionKind.Range ? "base..head" : null,
            },
            OpenBaseAsync = before.OpenAsync,
            OpenHeadAsync = after.OpenAsync,
            Components = components ?? [],
        };

    private static ChangeComponentInput Component(
        string selector,
        ChangeState before,
        ChangeState after) => new()
        {
            Selector = selector,
            BaseObjectId = before.ObjectId,
            HeadObjectId = after.ObjectId,
            OpenBaseAsync = before.OpenAsync,
            OpenHeadAsync = after.OpenAsync,
        };

    private static ChangeSnapshotReference Reference(string selector, string objectId) => new()
    {
        Selector = selector,
        ObjectId = objectId,
        Kind = ChangeSnapshotKind.GitTree,
    };

    private static ChangeState State(params (string Path, string Content)[] files)
    {
        InMemoryChangeSnapshot snapshot = new(files);
        return new ChangeState(snapshot.ObjectId, InMemoryChangeSnapshot.Factory(files));
    }

    private sealed record ChangeState(
        string ObjectId,
        Func<CancellationToken, Task<IChangeSnapshot>> OpenAsync);
}
