using System.Text;
using EffortHours.Analysis;
using EffortHours.Analyzers.Cpp;
using EffortHours.Contracts;
using EffortHours.Contracts.V1;
using EffortHours.Core;

namespace EffortHours.Tests;

public sealed class CppAnalyzerSafetyTests
{
    private const string Analyzer = "efforthours.cpp-analyzer";

    [Fact]
    public async Task GeneratedVendoredBuildOutputsAndPrivateLiteralsAreNotAnalyzedOrDisclosed()
    {
        InMemoryRepository repository = new();
        repository.WriteText("src/main.cpp", "const char* marker = \"private-source-marker\"; int main() { return 0; }\n");
        repository.WriteText("vendor/lib.cpp", "const char* marker = \"vendor-secret\";\n");
        repository.WriteText("generated/client.cpp", "// generated by tool\nconst char* marker = \"generated-secret\";\n");
        repository.WriteText("out/unity.cpp", "const char* marker = \"output-secret\";\n");

        RepositoryEvidence evidence = await ScanAsync(repository);
        string json = ContractJson.Serialize(evidence);

        Assert.Contains(evidence.Facts, fact => fact.Provenance.Analyzer == Analyzer &&
            fact.Locations.Any(location => location.Path == "src/main.cpp"));
        Assert.DoesNotContain(evidence.Facts.Where(fact => fact.Provenance.Analyzer == Analyzer)
            .SelectMany(fact => fact.Locations), location =>
                location.Path.StartsWith("vendor/", StringComparison.Ordinal) ||
                location.Path.StartsWith("generated/", StringComparison.Ordinal) ||
                location.Path.StartsWith("out/", StringComparison.Ordinal));
        Assert.DoesNotContain("private-source-marker", json, StringComparison.Ordinal);
        Assert.DoesNotContain("vendor-secret", json, StringComparison.Ordinal);
        Assert.DoesNotContain("generated-secret", json, StringComparison.Ordinal);
        Assert.DoesNotContain("output-secret", json, StringComparison.Ordinal);
    }

    [Fact]
    public async Task DigestChangesInvalidUtf8AndMalformedPreprocessorFailClosed()
    {
        InMemoryRepository changed = new();
        changed.WriteText("src/value.cpp", "struct Before {};\n");
        RepositoryEvidence common = await new RepositoryScanner(changed).ScanAsync(changed.RootPath);
        changed.WriteText("src/value.cpp", "struct After {};\n");

        RepositoryAnalysisContribution contribution = await new CppRepositoryAnalyzer(changed)
            .AnalyzeAsync(changed.RootPath, common);

        Assert.Contains(contribution.Diagnostics, diagnostic => diagnostic.Code == "FB8901" &&
            diagnostic.Message.Contains("changed after common scanning", StringComparison.Ordinal));
        Assert.DoesNotContain(contribution.Facts, fact => fact.Kind == EvidenceKinds.SourceStructure);

        InMemoryRepository malformed = new();
        malformed.WriteText("src/value.cpp", "#if FEATURE\nstruct Value { const char* x = R\"tag(open;\n");
        RepositoryEvidence malformedEvidence = await ScanAsync(malformed);
        Assert.Contains(malformedEvidence.Diagnostics, diagnostic => diagnostic.Code == "FB8902");
        Assert.Empty(ContractValidation.Validate(malformedEvidence));

        InMemoryRepository invalid = new();
        invalid.WriteBytes("src/value.cpp", [0xc3, 0x28]);
        RepositoryEvidence invalidEvidence = await ScanAsync(invalid);
        Assert.Contains(invalidEvidence.Diagnostics, diagnostic => diagnostic.Code == "FB8901");
    }

    [Fact]
    public void TokenizerBoundsRawStringsCommentsDirectivesAndConditionalNormalization()
    {
        CppTokenization valid = CppTokenizer.Tokenize(
            "/* comment */ #not_a_directive\n#define APPLY(x) #x\nconst char* value = R\"tag(text)tag\";\n");
        CppTokenization invalidRaw = CppTokenizer.Tokenize(
            "const char* value = R\"bad delim(text)bad delim\";\n");
        CppTokenization truncated = CppTokenizer.Tokenize(
            string.Join(' ', Enumerable.Repeat("identifier", CppTokenizer.MaximumTokens + 1)));
        CppSyntaxAnalysis conditional = CppSyntaxAnalyzer.Analyze(
            "#if ONE\nstruct Value {};\n#else\nstruct Value {};\n#endif\n",
            "include/value.hpp");

        Assert.Equal("medium", valid.Confidence);
        Assert.Contains(valid.Tokens, token => token.Kind == CppTokenKind.String);
        Assert.Contains(valid.Tokens, token => token.Kind == CppTokenKind.Preprocessor);
        Assert.Equal("low", invalidRaw.Confidence);
        Assert.True(truncated.Truncated);
        CppSyntaxAnalysis bounded = CppSyntaxAnalyzer.Analyze(
            string.Join(' ', Enumerable.Repeat("identifier", CppTokenizer.MaximumTokens + 1)),
            "src/large.cpp");
        Assert.Equal("low", bounded.Confidence);
        Assert.Equal(0, bounded.Metrics.Functions);
        CppTokenization arithmetic = CppTokenizer.Tokenize("int value = 1+2-3;\n");
        Assert.Contains(arithmetic.Tokens, token => token.Text == "+");
        Assert.Contains(arithmetic.Tokens, token => token.Text == "-");
        Assert.Equal(1, conditional.Metrics.Types);
        Assert.Equal(1, conditional.Preprocessor.ConditionalGroups);
        Assert.Equal(2, conditional.Preprocessor.ConditionalBranches);
    }

    [Fact]
    public void TokenizationHonorsCancellation()
    {
        using CancellationTokenSource cancellation = new();
        cancellation.Cancel();

        Assert.Throws<OperationCanceledException>(() =>
            CppTokenizer.Tokenize("int value = 1;", cancellation.Token));
    }

    [Fact]
    public void ConditionalAlternativesKeepDistinctPublicDeclarationsWithoutStackingResidualBodies()
    {
        CppSyntaxAnalysis analysis = CppSyntaxAnalyzer.Analyze(
            "#if WINDOWS\nint windows_api() { return 1; }\n" +
            "#else\nint unix_api() { return 2; }\n#endif\n",
            "include/platform.hpp");

        Assert.Equal(1, analysis.Metrics.Functions);
        Assert.Equal(2, analysis.Metrics.PublicSymbols);
    }

    private static Task<RepositoryEvidence> ScanAsync(InMemoryRepository repository) =>
        new RepositoryAnalysisPipeline(repository).ScanAsync(repository.RootPath);
}
