using EffortHours.Change;
using EffortHours.Contracts.V1;

namespace EffortHours.Tests;

public sealed class CppChangeTests
{
    [Fact]
    public async Task WhitespaceAndOrdinaryCommentOnlyCppChangeHasZeroEffort()
    {
        const string before =
            "// old note\ntemplate<class T> struct Store { T run(const T& value) { return value; } };\n";
        const string after =
            "/* replacement note */\ntemplate < class T >\nstruct Store\n{\n    T run( const T & value )\n    {\n        return value ;\n    }\n};\n";

        ChangeEstimateReport report = await EstimateAsync(
            State(("include/store.hpp", before)),
            State(("include/store.hpp", after)));

        Assert.Equal(ChangePathClassification.FormattingOnly, Assert.Single(report.Evidence.Paths).Classification);
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Fact]
    public async Task WhitespaceAndOrdinaryCommentOnlyCChangeHasZeroEffort()
    {
        ChangeEstimateReport report = await EstimateAsync(
            State(("src/value.c", "/* old */ int value(int input) { return input + 1; }\n")),
            State(("src/value.c", "// replacement\nint value( int input )\n{\n return input + 1 ;\n}\n")));

        Assert.Equal(ChangePathClassification.FormattingOnly,
            Assert.Single(report.Evidence.Paths).Classification);
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Fact]
    public async Task ExactMoveCopyAndGeneratedCppBodiesRemainExcluded()
    {
        const string body = "int value() { return 1; }\n";
        ChangeEstimateReport move = await EstimateAsync(
            State(("src/value.cpp", body)),
            State(("native/value.cpp", body)));
        ChangeEstimateReport copyAndGenerated = await EstimateAsync(
            State(("src/value.cpp", body)),
            State(
                ("src/value.cpp", body),
                ("src/value_copy.cpp", body),
                ("generated/client.generated.cpp", "// <auto-generated />\nint generated() { return 2; }\n")));

        ChangePathEvidence moved = Assert.Single(move.Evidence.Paths);
        Assert.Equal(ChangePathStatus.Moved, moved.Status);
        Assert.Equal(ChangePathClassification.ExactMove, moved.Classification);
        Assert.Equal(0m, move.TotalEffort.Expected);
        Assert.Contains(copyAndGenerated.Evidence.Paths, path =>
            path.Path == "src/value_copy.cpp" &&
            path.Classification == ChangePathClassification.ExactDuplicate &&
            !path.Represented);
        Assert.Contains(copyAndGenerated.Evidence.Paths, path =>
            path.Path == "generated/client.generated.cpp" &&
            path.Classification == ChangePathClassification.Generated &&
            !path.Represented);
        Assert.Equal(0m, copyAndGenerated.TotalEffort.Expected);
    }

    [Theory]
    [InlineData("const char* value = R\"tag(before)tag\";\n", "const char* value = R\"tag(after)tag\";\n")]
    [InlineData("/// Before contract.\nint run();\n", "/// After contract.\nint run();\n")]
    [InlineData("#define MODE 1\nint run();\n", "#define MODE 2\nint run();\n")]
    [InlineData("#if ONE\nint run();\n#endif\n", "#if TWO\nint run();\n#endif\n")]
    [InlineData("[[nodiscard]] int run();\n", "int run();\n")]
    public async Task LiteralsDocumentationDirectivesConditionsAndAttributesRemainMeaningful(
        string before,
        string after)
    {
        ChangeEstimateReport report = await EstimateAsync(
            State(("include/value.hpp", before)),
            State(("include/value.hpp", after)));

        Assert.True(Assert.Single(report.Evidence.Paths).Represented);
        Assert.True(report.TotalEffort.Expected > 0m);
    }

    [Fact]
    public async Task UnterminatedRawStringOrDelimiterFailsClosed()
    {
        ChangeEstimateReport report = await EstimateAsync(
            State(("src/value.cpp", "const char* value = R\"tag(open;\n")),
            State(("src/value.cpp", "const char * value=R\"tag(open;\n")));

        Assert.True(Assert.Single(report.Evidence.Paths).Represented);
        Assert.True(report.TotalEffort.Expected > 0m);
    }

    [Fact]
    public async Task InvalidRawDelimiterAndExponentAdjacencyFailClosed()
    {
        ChangeEstimateReport raw = await EstimateAsync(
            State(("src/value.cpp", "const char* value = R\"bad delim(text)bad delim\";\n")),
            State(("src/value.cpp", "const char * value=R\"bad delim(text)bad delim\" ;\n")));
        ChangeEstimateReport exponent = await EstimateAsync(
            State(("src/value.cpp", "double value = 1e+2;\n")),
            State(("src/value.cpp", "double value = 1e + 2;\n")));

        Assert.True(Assert.Single(raw.Evidence.Paths).Represented);
        Assert.True(raw.TotalEffort.Expected > 0m);
        Assert.True(Assert.Single(exponent.Evidence.Paths).Represented);
        Assert.True(exponent.TotalEffort.Expected > 0m);
    }

    [Fact]
    public async Task UnbalancedOrRepeatedConditionalDirectiveFailsClosed()
    {
        ChangeEstimateReport unbalanced = await EstimateAsync(
            State(("src/value.cpp", "#if FEATURE\nint value = 1;\n")),
            State(("src/value.cpp", "#if FEATURE\nint  value=1 ;\n")));
        ChangeEstimateReport repeatedElse = await EstimateAsync(
            State(("src/value.cpp", "#if FEATURE\nint value = 1;\n#else\nint value = 2;\n#else\nint value = 3;\n#endif\n")),
            State(("src/value.cpp", "#if FEATURE\nint  value=1;\n#else\nint value=2;\n#else\nint value=3;\n#endif\n")));

        Assert.True(Assert.Single(unbalanced.Evidence.Paths).Represented);
        Assert.True(unbalanced.TotalEffort.Expected > 0m);
        Assert.True(Assert.Single(repeatedElse.Evidence.Paths).Represented);
        Assert.True(repeatedElse.TotalEffort.Expected > 0m);
    }

    [Fact]
    public async Task AddedCppBuildSourceHeadersAndTestsReachSemanticCategories()
    {
        ChangeEstimateReport report = await EstimateAsync(
            State(),
            State(
                ("CMakeLists.txt",
                    "find_package(gRPC REQUIRED)\nfind_package(SQLite3 REQUIRED)\n" +
                    "find_package(OpenSSL REQUIRED)\nfind_package(GTest REQUIRED)\n" +
                    "add_executable(app src/main.cpp include/api.hpp)\n" +
                    "target_link_libraries(app PRIVATE gRPC SQLite3 OpenSSL)\n" +
                    "add_executable(tests tests/api_test.cpp)\ntarget_link_libraries(tests PRIVATE GTest)\n"),
                ("include/api.hpp", "#pragma once\nextern \"C\" int native_status();\nstruct Api { int run(); };\n"),
                ("src/main.cpp",
                    "#include \"../include/api.hpp\"\n#include <grpcpp/grpcpp.h>\n#include <sqlite3.h>\n" +
                    "#include <openssl/evp.h>\nstruct Server { void route(); }; struct Connection { void query(); };\n" +
                    "int main() { Server server; server.route(); Connection db; db.query(); " +
                    "EVP_DigestVerifyInit(nullptr,nullptr,nullptr,nullptr,nullptr); return native_status(); }\n"),
                ("tests/api_test.cpp", "#include <gtest/gtest.h>\nTEST(Api, Runs) { EXPECT_EQ(1, 1); }\n")));

        Assert.Contains(report.Categories, item =>
            item.Category == EffortCategory.ProductionImplementation && item.Hours.Expected > 0m);
        Assert.Contains(report.Categories, item =>
            item.Category == EffortCategory.DataModelingPersistenceAndMigrations && item.Hours.Expected > 0m);
        Assert.Contains(report.Categories, item =>
            item.Category == EffortCategory.ExternalIntegrationsAndProtocols && item.Hours.Expected > 0m);
        Assert.Contains(report.Categories, item =>
            item.Category == EffortCategory.SecurityAndAccessibility && item.Hours.Expected > 0m);
        Assert.Contains(report.Categories, item =>
            item.Category == EffortCategory.UnitTesting && item.Hours.Expected > 0m);
        Assert.Contains(report.Categories, item =>
            item.Category == EffortCategory.BuildConfigurationAndDeveloperTooling && item.Hours.Expected > 0m);
        Assert.Equal("change-seed/0.18.1+seed-rules/0.4.0", report.EstimatorVersion);
    }

    [Fact]
    public async Task OneHeaderChangeIsNotMultipliedByIncludeFanout()
    {
        ChangeState before = State(
            ("include/value.hpp", "struct Value { int id; };\n"),
            ("src/one.cpp", "#include \"../include/value.hpp\"\nint one() { return 1; }\n"),
            ("src/two.cpp", "#include \"../include/value.hpp\"\nint two() { return 2; }\n"));
        ChangeState after = State(
            ("include/value.hpp", "struct Value { long id; };\n"),
            ("src/one.cpp", "#include \"../include/value.hpp\"\nint one() { return 1; }\n"),
            ("src/two.cpp", "#include \"../include/value.hpp\"\nint two() { return 2; }\n"));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        Assert.Single(report.Evidence.Paths);
        Assert.InRange(report.TotalEffort.Expected, 0.5m, 8m);
        Assert.DoesNotContain(report.WorkItems, item => item.Title.Contains("translation unit", StringComparison.OrdinalIgnoreCase));
    }

    private static Task<ChangeEstimateReport> EstimateAsync(ChangeState before, ChangeState after) =>
        new ChangeEstimator().EstimateAsync(
            new ChangeEstimateInput
            {
                RepositoryName = "in-memory-cpp-change",
                Selection = new ChangeSelection
                {
                    Kind = ChangeSelectionKind.BaseHead,
                    Base = Reference("base", before.ObjectId),
                    Head = Reference("head", after.ObjectId),
                },
                OpenBaseAsync = before.OpenAsync,
                OpenHeadAsync = after.OpenAsync,
            },
            EstimationProfile.Implementation);

    private static ChangeSnapshotReference Reference(string selector, string objectId) => new()
    {
        Selector = selector,
        ObjectId = objectId,
        Kind = ChangeSnapshotKind.GitTree,
    };

    private static ChangeState State(params (string Path, string Content)[] files)
    {
        InMemoryChangeSnapshot snapshot = new(files);
        return new ChangeState(snapshot.ObjectId, InMemoryChangeSnapshot.Factory(files));
    }

    private sealed record ChangeState(
        string ObjectId,
        Func<CancellationToken, Task<IChangeSnapshot>> OpenAsync);
}
