using EffortHours.Change;
using EffortHours.Contracts;
using EffortHours.Contracts.V1;
using EffortHours.Core;
using EffortHours.Estimation;

namespace EffortHours.Tests;

public sealed class DotNetSourceBindingTests
{
    private const string Project = "<Project Sdk=\"Microsoft.NET.Sdk\" />";

    [Fact]
    public async Task AggregateLocationsRetainExactOwnedParsedFilesWithoutChangingStock()
    {
        InMemoryRepository repository = new();
        repository.WriteText("App.csproj", Project);
        repository.WriteText("Root.cs", "public class Root { public void Run() { } }");
        repository.WriteText("nested/Library.csproj", Project);
        repository.WriteText("nested/Library.cs", "public class Library { public void Act() { } }");
        repository.WriteText("nested/Generated.g.cs", "// <auto-generated />\npublic class Generated { }");
        RepositoryEvidence evidence = await new RepositoryAnalysisPipeline(repository).ScanAsync(repository.RootPath);
        EvidenceFact root = Assert.Single(evidence.Facts, fact => fact.Id == "dotnet:source-structure:App.csproj");
        EvidenceFact nested = Assert.Single(evidence.Facts, fact => fact.Id == "dotnet:source-structure:nested/Library.csproj");
        Assert.Equal(["Root.cs"], root.Locations.Select(location => location.Path));
        Assert.Equal(["nested/Library.cs"], nested.Locations.Select(location => location.Path));
        Assert.Equal("0.3.6", root.Provenance.AnalyzerVersion);
        RepositoryEvidence legacy = evidence with
        {
            Facts = [.. evidence.Facts.Select(fact => fact.Kind == EvidenceKinds.SourceStructure
                ? fact with { Locations = [] } : fact)],
        };
        SeedEstimator seed = new();
        Assert.Equal(ContractJson.Serialize(seed.Estimate(legacy, EstimationProfile.Implementation)),
            ContractJson.Serialize(seed.Estimate(evidence, EstimationProfile.Implementation)));
        string json = ContractJson.Serialize(evidence);
        Assert.True(ContractSchemaValidator.Validate(SchemaNames.RepositoryEvidence, json).IsValid);
        Assert.Empty(ContractValidation.Validate(evidence));
    }

    [Fact]
    public async Task ProjectGrowthUsesOnlyItsSourceAndKeepsOtherRolesIndependent()
    {
        (string Path, string Content)[] before =
        [
            ("App.csproj", Project),
            ("Main.cs", "public class Main { public void Before() { } }"),
            ("nested/Library.csproj", Project),
            ("nested/Library.cs", "public class Library { public void Before() { } }"),
            ("tests/App.Tests.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><IsTestProject>true</IsTestProject></PropertyGroup></Project>"),
            ("tests/Tests.cs", "public class Tests { [Fact] public void Before() { Assert.True(true); } }"),
            ("guide.md", "# Before"),
        ];
        (string Path, string Content)[] after = [.. before.Select(file => file.Path switch
        {
            "Main.cs" => (file.Path, "public class Main { public void After() { } public void More() { } }"),
            "nested/Library.cs" => (file.Path, "public class Library { public void After() { } public void Extra() { } }"),
            "tests/Tests.cs" => (file.Path, "public class Tests { [Fact] public void After() { Assert.False(false); } [Fact] public void More() { Assert.True(true); } }"),
            "guide.md" => (file.Path, "# After\n\nAn expanded usage guide."),
            _ => file,
        })];
        ChangeEstimateReport report = await new ChangeEstimator().EstimateAsync(new ChangeEstimateInput
        {
            RepositoryName = "synthetic-scopes",
            Selection = new ChangeSelection
            {
                Kind = ChangeSelectionKind.BaseHead,
                Base = Reference("base", before),
                Head = Reference("head", after),
            },
            OpenBaseAsync = InMemoryChangeSnapshot.Factory(before),
            OpenHeadAsync = InMemoryChangeSnapshot.Factory(after),
        }, EstimationProfile.Implementation);
        WorkItem[] production = [.. report.WorkItems.Where(item => item.Category == EffortCategory.ProductionImplementation)];
        Assert.NotEmpty(production);
        foreach (WorkItem item in production)
        {
            string expectedPath = item.Scope == "App.csproj" ? "Main.cs" : "nested/Library.cs";
            Assert.Equal([expectedPath], item.EvidenceIds.Select(id =>
                Assert.Single(report.Evidence.Paths, path => path.Id == id).Path));
        }
        Assert.Contains(report.WorkItems, item => item.Category == EffortCategory.UnitTesting);
        Assert.Contains(report.WorkItems, item => item.Category == EffortCategory.Documentation);
        Assert.Empty(ContractValidation.Validate(report));
        Assert.True(ContractSchemaValidator.Validate(SchemaNames.ChangeEstimateReport, ContractJson.Serialize(report)).IsValid);
    }

    private static ChangeSnapshotReference Reference(string selector, (string Path, string Content)[] files) => new()
    {
        Selector = selector,
        ObjectId = new InMemoryChangeSnapshot(files).ObjectId,
        Kind = ChangeSnapshotKind.GitTree,
    };
}
