using EffortHours.Change;
using EffortHours.Contracts.V1;

namespace EffortHours.Tests;

public sealed class GeneratedCustomizationTests
{
    private const string ProjectFile =
        "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup>" +
        "<TargetFramework>net10.0</TargetFramework>" +
        "</PropertyGroup></Project>\n";

    [Fact]
    public async Task GeneratedBodyChangeWithUnchangedCustomRegionRemainsExcluded()
    {
        ChangeEstimateReport report = await EstimateAsync(
            Generated("v1", "internal partial class Client { public int Timeout => 10; }"),
            Generated("v2", "internal partial class Client { public int Timeout => 10; }"));

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathClassification.Generated, path.Classification);
        Assert.False(path.Represented);
        Assert.Equal(0, path.EditRegions);
        Assert.Contains(
            "normalization:generated-customization-unchanged",
            path.Tags);
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Fact]
    public async Task ChangedCustomRegionRepresentsOnlyMaintainedProjection()
    {
        ChangeEstimateReport report = await EstimateAsync(
            Generated("v1", "internal partial class Client { public int Timeout => 10; }"),
            Generated("v2", "internal partial class Client { public int Timeout => 30; }"));

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathClassification.Represented, path.Classification);
        Assert.True(path.Represented);
        Assert.InRange(path.EditRegions, 1, 4);
        Assert.Contains("classification:generated", path.Tags);
        Assert.Contains(
            "normalization:generated-customization-represented",
            path.Tags);
        Assert.Contains("Only those maintained regions", path.Reason, StringComparison.Ordinal);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "FB5203");
        Assert.True(report.TotalEffort.Expected > 0m);
    }

    [Fact]
    public async Task FormattingOnlyCustomRegionChangeRemainsExcluded()
    {
        ChangeEstimateReport report = await EstimateAsync(
            Generated("v1", "internal partial class Client { public int Timeout => 10; }"),
            Generated(
                "v2",
                "internal partial class Client\n{\n    public int Timeout => 10;\n}"));

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathClassification.Generated, path.Classification);
        Assert.False(path.Represented);
        Assert.Contains(
            "normalization:generated-customization-formatting-only",
            path.Tags);
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public async Task AddedOrRemovedCustomRegionIsPositiveAndBounded(bool added)
    {
        ChangeState empty = State(("Demo.csproj", ProjectFile));
        ChangeState generated = State(
            ("Demo.csproj", ProjectFile),
            ("Generated.g.cs", Generated(
                "v1",
                "internal partial class Client { public int Timeout => 10; }")));

        ChangeEstimateReport report = added
            ? await EstimateAsync(empty, generated)
            : await EstimateAsync(generated, empty);

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(
            added ? ChangePathStatus.Added : ChangePathStatus.Removed,
            path.Status);
        Assert.Equal(ChangePathClassification.Represented, path.Classification);
        Assert.True(report.TotalEffort.Expected > 0m);
        Assert.All(report.WorkItems, item => Assert.InRange(item.Hours.Expected, 0.01m, 8m));
    }

    [Fact]
    public async Task AmbiguousMarkersFailClosedAndRequireReview()
    {
        string malformed =
            "// <auto-generated />\n" +
            "// <custom-code>\n" +
            "internal partial class Client { public int Timeout => 30; }\n";

        ChangeEstimateReport report = await EstimateAsync(
            Generated("v1", "internal partial class Client { public int Timeout => 10; }"),
            malformed);

        ChangePathEvidence path = Assert.Single(report.Evidence.Paths);
        Assert.Equal(ChangePathClassification.Generated, path.Classification);
        Assert.False(path.Represented);
        Assert.Contains(
            "normalization:generated-customization-ambiguous",
            path.Tags);
        Assert.Contains("unclosed", path.Reason, StringComparison.OrdinalIgnoreCase);
        Assert.Contains(report.Diagnostics, diagnostic => diagnostic.Code == "FB5204");
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Theory]
    [InlineData("obj/Generated.g.cs", ChangePathClassification.BuildOutput)]
    [InlineData("vendor/Generated.g.cs", ChangePathClassification.Vendored)]
    [InlineData("assets/client.min.js", ChangePathClassification.Minified)]
    [InlineData("generated/client.dll", ChangePathClassification.Binary)]
    [InlineData("package-lock.json", ChangePathClassification.Lockfile)]
    public async Task StrongerMechanicalExclusionsWinOverCustomMarkers(
        string path,
        ChangePathClassification expectedClassification)
    {
        ChangeState before = State(("Demo.csproj", ProjectFile));
        ChangeState after = State(
            ("Demo.csproj", ProjectFile),
            (path, Generated(
                "v1",
                "internal partial class Client { public int Timeout => 10; }")));

        ChangeEstimateReport report = await EstimateAsync(before, after);

        ChangePathEvidence evidence = Assert.Single(report.Evidence.Paths);
        Assert.Equal(expectedClassification, evidence.Classification);
        Assert.False(evidence.Represented);
        Assert.DoesNotContain(
            "normalization:generated-customization-represented",
            evidence.Tags);
        Assert.Equal(0m, report.TotalEffort.Expected);
    }

    [Theory]
    [InlineData("// <custom-code>", "// </custom-code>")]
    [InlineData("/* <custom-code> */", "/* </custom-code> */")]
    [InlineData("# <custom-code>", "# </custom-code>")]
    [InlineData("<!-- <custom-code> -->", "<!-- </custom-code> -->")]
    [InlineData("// <CUSTOM-CODE>", "// </CUSTOM-CODE>")]
    public void ExactSupportedMarkerStylesIsolateCustomContent(string start, string end)
    {
        byte[] before = System.Text.Encoding.UTF8.GetBytes(
            $"generated-v1\n{start}\nconst value = 1;\n{end}\n");
        byte[] after = System.Text.Encoding.UTF8.GetBytes(
            $"generated-v2\n{start}\nconst value = 2;\n{end}\n");

        GeneratedCustomizationResult result = GeneratedCustomizationAnalyzer.Analyze(
            before,
            after,
            "client.js");

        Assert.Equal(GeneratedCustomizationOutcome.Represented, result.Outcome);
        Assert.Equal(1, result.MeaningfulRegionCount);
        Assert.True(result.EditRegions > 0);
    }

    [Fact]
    public void GeneratorSpecificOrNearMatchMarkersAreNotInferred()
    {
        byte[] before = System.Text.Encoding.UTF8.GetBytes(
            "generated-v1\n// region Custom Code\nconst value = 1;\n// endregion\n");
        byte[] after = System.Text.Encoding.UTF8.GetBytes(
            "generated-v2\n// <custom-code> trailing\nconst value = 2;\n// </custom-code> trailing\n");

        GeneratedCustomizationResult result = GeneratedCustomizationAnalyzer.Analyze(
            before,
            after,
            "client.js");

        Assert.Equal(GeneratedCustomizationOutcome.NotDetected, result.Outcome);
    }

    private static string Generated(string version, string customCode) =>
        "// <auto-generated />\n" +
        $"// generated body {version}\n" +
        "namespace Demo;\n" +
        "// <custom-code>\n" +
        customCode + "\n" +
        "// </custom-code>\n";

    private static Task<ChangeEstimateReport> EstimateAsync(string before, string after) =>
        EstimateAsync(
            State(("Demo.csproj", ProjectFile), ("Generated.g.cs", before)),
            State(("Demo.csproj", ProjectFile), ("Generated.g.cs", after)));

    private static Task<ChangeEstimateReport> EstimateAsync(
        ChangeState before,
        ChangeState after) => new ChangeEstimator().EstimateAsync(
            new ChangeEstimateInput
            {
                RepositoryName = "generated-customization",
                Selection = new ChangeSelection
                {
                    Kind = ChangeSelectionKind.BaseHead,
                    Base = Reference("base", before.ObjectId),
                    Head = Reference("head", after.ObjectId),
                },
                OpenBaseAsync = before.OpenAsync,
                OpenHeadAsync = after.OpenAsync,
            },
            EstimationProfile.Implementation);

    private static ChangeSnapshotReference Reference(string selector, string objectId) => new()
    {
        Selector = selector,
        ObjectId = objectId,
        Kind = ChangeSnapshotKind.GitTree,
    };

    private static ChangeState State(params (string Path, string Content)[] files)
    {
        InMemoryChangeSnapshot snapshot = new(files);
        return new ChangeState(snapshot.ObjectId, InMemoryChangeSnapshot.Factory(files));
    }

    private sealed record ChangeState(
        string ObjectId,
        Func<CancellationToken, Task<IChangeSnapshot>> OpenAsync);
}
