using EffortHours.Analysis;
using EffortHours.Contracts;
using EffortHours.Contracts.V1;

namespace EffortHours.Tests;

public sealed class RepositoryScannerTests
{
    [Fact]
    public async Task ScanProducesValidDeterministicEvidenceForMixedRepository()
    {
        InMemoryRepository repository = new();
        repository.WriteText("Demo.slnx", "<Solution />\n");
        repository.WriteText("src/server/Server.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        repository.WriteText(
            "src/server/Program.cs",
            "namespace Demo;\npublic static class Program { private const string Value = \"source-only-marker\"; }\n");
        repository.WriteText(
            "src/server/Api.generated.cs",
            "// <auto-generated />\nnamespace Demo;\npublic sealed class GeneratedApi;\n");
        repository.WriteText("src/web/package.json", "{\"scripts\":{\"test\":\"vitest\"}}\n");
        repository.WriteText("src/web/tsconfig.json", "{\"compilerOptions\":{\"strict\":true}}\n");
        repository.WriteText("src/web/app.ts", "export const answer: number = 42;\n");
        repository.WriteText("src/web/app.min.js", new string('x', 1500));
        repository.WriteText("tests/Server.Tests/Server.Tests.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />\n");
        repository.WriteText("tests/Server.Tests/CalculatorTests.cs", "public sealed class CalculatorTests { }\n");
        repository.WriteText("README.md", "# Demo\n\nSynthetic documentation.\n");
        repository.WriteText(".github/workflows/ci.yml", "name: ci\n");
        repository.WriteText("infra/main.tf", "terraform { required_version = \">= 1.0\" }\n");
        repository.WriteText("Dockerfile", "FROM scratch\n");
        repository.WriteBytes("coverage/results.coverage", [0x00, 0x01, 0x02]);
        repository.WriteBytes("assets/logo.png", [0x89, 0x50, 0x4e, 0x47, 0x00, 0x01]);
        repository.WriteText(".gitignore", "ignored/\n[Dd]ebug/\n[z-a]\n*.tmp\n!keep.tmp\n");
        repository.WriteText(".efforthoursignore", "local-only/\n");
        repository.WriteText("ignored/private.cs", "ignored source\n");
        repository.WriteText("Debug/debug.cs", "ignored debug output\n");
        repository.WriteText("local-only/calibration.json", "private local data\n");
        repository.WriteText("scratch.tmp", "ignored scratch\n");
        repository.WriteText("keep.tmp", "explicitly included\n");
        repository.WriteText("node_modules/pkg/index.js", "vendored dependency\n");
        repository.WriteText("src/server/obj/generated.cs", "build output\n");
        repository.WriteText(".git/objects/01", "history must not be inspected\n");
        repository.WriteText("src/web/.gitignore", "private/\n");
        repository.WriteText("src/web/private/settings.ts", "ignored nested source\n");

        RepositoryScanner scanner = new(repository);
        RepositoryEvidence first = await scanner.ScanAsync(repository.RootPath);
        RepositoryEvidence second = await scanner.ScanAsync(repository.RootPath);
        string firstJson = ContractJson.Serialize(first);
        string secondJson = ContractJson.Serialize(second);

        Assert.Equal(firstJson, secondJson);
        Assert.Empty(ContractValidation.Validate(first));
        SchemaValidationResult schema = ContractSchemaValidator.Validate(
            SchemaNames.RepositoryEvidence,
            firstJson);
        Assert.True(schema.IsValid, string.Join(Environment.NewLine, schema.Errors));
        Assert.Equal(["docker", "dotnet", "javascript", "terraform", "typescript"], first.Repository.Ecosystems);
        Assert.StartsWith("sha256:", first.Repository.SourceDigest, StringComparison.Ordinal);
        Assert.DoesNotContain(repository.RootPath, firstJson, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("source-only-marker", firstJson, StringComparison.Ordinal);

        AssertFileHasTag(first, "src/server/Api.generated.cs", "classification:generated");
        AssertFileHasTag(first, "src/web/app.min.js", "classification:minified");
        AssertFileHasTag(first, "assets/logo.png", "content:binary");
        AssertFileHasTag(first, "tests/Server.Tests/CalculatorTests.cs", "classification:test");
        AssertFileHasTag(first, "infra/main.tf", "language:terraform");
        Assert.Contains(first.Facts, fact => fact.Id == "file:keep.tmp");
        Assert.Contains(first.Facts, fact => fact.Id == "tests:repository");
        Assert.Contains(first.Facts, fact => fact.Id == "documentation:repository");
        Assert.Contains(first.Facts, fact => fact.Id == "ci:repository");
        Assert.Contains(first.Facts, fact => fact.Id == "containers:repository");
        Assert.Contains(first.Facts, fact => fact.Id == "infrastructure:repository");
        Assert.Contains(first.Facts, fact => fact.Id == "coverage:repository");

        AssertExcluded(first, ".git", "reason:version-control-metadata");
        AssertExcluded(first, "node_modules", "reason:vendored-dependencies");
        AssertExcluded(first, "src/server/obj", "reason:build-output");
        AssertExcluded(first, "ignored", "reason:ignore-rule");
        AssertExcluded(first, "Debug", "reason:ignore-rule");
        AssertExcluded(first, "local-only", "reason:ignore-rule");
        AssertExcluded(first, "scratch.tmp", "reason:ignore-rule");
        AssertExcluded(first, "src/web/private", "reason:ignore-rule");
        Assert.DoesNotContain(first.Facts, fact => fact.Id == "file:ignored/private.cs");
        Assert.All(
            first.Facts.SelectMany(fact => fact.Locations),
            location => Assert.DoesNotContain('\\', location.Path));
    }

    [Fact]
    public async Task SourceDigestExcludesIgnoredContentAndTracksIncludedContent()
    {
        InMemoryRepository repository = new();
        repository.WriteText(".gitignore", "ignored/\n");
        repository.WriteText("src/app.ts", "export const value = 1;\n");
        repository.WriteText("ignored/cache.txt", "first ignored value\n");
        RepositoryScanner scanner = new(repository);

        string? originalDigest = (await scanner.ScanAsync(repository.RootPath)).Repository.SourceDigest;
        repository.WriteText("ignored/cache.txt", "second ignored value\n");
        string? ignoredChangeDigest = (await scanner.ScanAsync(repository.RootPath)).Repository.SourceDigest;
        repository.WriteText("src/app.ts", "export const value = 2;\n");
        string? sourceChangeDigest = (await scanner.ScanAsync(repository.RootPath)).Repository.SourceDigest;

        Assert.Equal(originalDigest, ignoredChangeDigest);
        Assert.NotEqual(originalDigest, sourceChangeDigest);
    }

    [Fact]
    public async Task ScanCanDisableGitIgnoreHandling()
    {
        InMemoryRepository repository = new();
        repository.WriteText(".gitignore", "hidden.ts\n");
        repository.WriteText("hidden.ts", "export const visibleWhenRequested = true;\n");
        RepositoryScanner scanner = new(repository);

        RepositoryEvidence defaultEvidence = await scanner.ScanAsync(repository.RootPath);
        RepositoryEvidence inclusiveEvidence = await scanner.ScanAsync(
            repository.RootPath,
            new RepositoryScanOptions { RespectGitIgnore = false });

        Assert.DoesNotContain(defaultEvidence.Facts, fact => fact.Id == "file:hidden.ts");
        Assert.Contains(inclusiveEvidence.Facts, fact => fact.Id == "file:hidden.ts");
    }

    [Fact]
    public async Task ScanDoesNotWriteToTheTargetRepository()
    {
        InMemoryRepository repository = new();
        repository.WriteText("src/index.js", "export const ready = true;\n");
        string[] before = repository.EnumerateRelativeFiles();

        _ = await new RepositoryScanner(repository).ScanAsync(repository.RootPath);

        Assert.Equal(before, repository.EnumerateRelativeFiles());
    }

    [Fact]
    public async Task ExplicitExternalCacheIsVersionedAndDoesNotChangeEvidence()
    {
        InMemoryRepository repository = new();
        InMemoryScanCacheStore cacheStore = new();
        repository.WriteText("src/index.ts", "export const cachedMarker = 1;\n");
        string cachePath = Path.GetFullPath(Path.Combine(
            repository.RootPath,
            "..",
            "scan-cache.json"));
        RepositoryScanOptions options = new() { CachePath = cachePath };
        RepositoryScanner scanner = new(repository, cacheStore);

        RepositoryEvidence first = await scanner.ScanAsync(repository.RootPath, options);
        RepositoryEvidence second = await scanner.ScanAsync(repository.RootPath, options);

        Assert.Equal(ContractJson.Serialize(first), ContractJson.Serialize(second));
        Assert.True(cacheStore.Exists(cachePath));
        string cacheJson = cacheStore.ReadAllText(cachePath);
        RepositoryScanCache cache = ContractJson.Deserialize<RepositoryScanCache>(cacheJson);
        Assert.Empty(ContractValidation.Validate(cache));
        SchemaValidationResult cacheSchema = ContractSchemaValidator.Validate(
            SchemaNames.RepositoryScanCache,
            cacheJson);
        Assert.True(cacheSchema.IsValid, string.Join(Environment.NewLine, cacheSchema.Errors));
        Assert.Equal(RepositoryScanner.AnalyzerVersion, cache.AnalyzerVersion);
        Assert.DoesNotContain("cachedMarker", cacheJson, StringComparison.Ordinal);

        repository.WriteText("src/index.ts", "export const cachedMarker = 200;\n");
        RepositoryEvidence changed = await scanner.ScanAsync(repository.RootPath, options);
        Assert.NotEqual(first.Repository.SourceDigest, changed.Repository.SourceDigest);
    }

    [Fact]
    public async Task CacheCannotWriteInsideTargetRepository()
    {
        InMemoryRepository repository = new();
        repository.WriteText("src/index.js", "export const ready = true;\n");
        RepositoryScanOptions options = new()
        {
            CachePath = Path.Combine(repository.RootPath, ".efforthours", "scan-cache.json"),
        };

        ArgumentException exception = await Assert.ThrowsAsync<ArgumentException>(
            () => new RepositoryScanner(repository).ScanAsync(repository.RootPath, options));

        Assert.Contains("outside", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task ScanRejectsMissingRepository()
    {
        InMemoryRepository repository = new();
        string missingPath = Path.Combine(repository.RootPath, "missing");

        await Assert.ThrowsAsync<DirectoryNotFoundException>(
            () => new RepositoryScanner(repository).ScanAsync(missingPath));
    }

    private static void AssertFileHasTag(
        RepositoryEvidence evidence,
        string path,
        string expectedTag)
    {
        EvidenceFact fact = Assert.Single(evidence.Facts, fact => fact.Id == $"file:{path}");
        Assert.Contains(expectedTag, fact.Tags);
    }

    private static void AssertExcluded(
        RepositoryEvidence evidence,
        string path,
        string expectedReason)
    {
        EvidenceFact fact = Assert.Single(evidence.Facts, fact => fact.Id == $"excluded:{path}");
        Assert.Contains(expectedReason, fact.Tags);
    }

}
