using EffortHours.Analysis;
using EffortHours.Change;
using EffortHours.Contracts;
using EffortHours.Contracts.V1;
using EffortHours.Core;
using EffortHours.Estimation;

namespace EffortHours.Tests;

public sealed partial class RepositoryEvidenceIncrementalDeriverTests
{
    [Theory]
    [InlineData("public sealed class Example { public int First() => 100; }",
        "public sealed class Example { public int Other() => 100; }")]
    [InlineData("public sealed class Example { public int First(int x) => x + 1; }",
        "public sealed class Example { public int First(int x) => x - 1; }")]
    [InlineData("public sealed class Example { public int First(int x) => x > 1 ? 1 : 2; }",
        "public sealed class Example { public int Other(int x) => x < 1 ? 1 : 2; }")]
    public async Task ExactLocalCSharpProofMatchesFullColdEvidenceAndStock(string before, string after)
    {
        Fixture fixture = await CreateFixtureAsync(before, after);
        RepositoryEvidence? derived = await RepositoryEvidenceIncrementalDeriver.TryDeriveAsync(
            fixture.Previous, fixture.Current, fixture.Current.RootPath, [PathName], CancellationToken.None);
        RepositoryEvidence cold = await new RepositoryAnalysisPipeline(fixture.Current,
            analysisArtifactCache: fixture.AnalysisCache).ScanAsync(fixture.Current.RootPath);
        Assert.NotNull(derived);
        derived = derived with { Repository = cold.Repository };
        Assert.Equal(ContractJson.Serialize(cold), ContractJson.Serialize(derived));
        SeedEstimator estimator = new();
        foreach (EstimationProfile profile in Enum.GetValues<EstimationProfile>())
        {
            EstimateReport previous = estimator.Estimate(fixture.Previous, profile);
            Assert.Equal(ContractJson.Serialize(estimator.Estimate(cold, profile)),
                ContractJson.Serialize(ChangeEstimator.RefreshDerivedEstimate(previous, derived)));
        }
    }

    [Theory]
    [InlineData("classification")]
    [InlineData("lines")]
    [InlineData("local-facts")]
    [InlineData("duplicate")]
    public async Task ExactLocalProofRejectsChangedCommonOrSemanticEvidence(string scenario)
    {
        string before = "// owned code padding padding\npublic class Example { public int First() => 100; }";
        string after = scenario switch
        {
            "classification" => "// <auto-generated> padding  \npublic class Example { public int Other() => 100; }",
            "lines" => "// owned code padding paddin\n\npublic class Example { public int Other() => 100; }",
            "local-facts" => "// owned code padding p\npublic class Example { [Fact]public int First() => 100; }",
            _ => before.Replace("First", "Other", StringComparison.Ordinal),
        };
        Assert.Equal(System.Text.Encoding.UTF8.GetByteCount(before), System.Text.Encoding.UTF8.GetByteCount(after));
        Fixture fixture = await CreateFixtureAsync(before, after);
        RepositoryEvidence previous = scenario == "duplicate" ? AddDuplicateDigest(fixture.Previous, Sha256(after))
            : fixture.Previous;
        Assert.Null(await RepositoryEvidenceIncrementalDeriver.TryDeriveAsync(previous,
            fixture.Current, fixture.Current.RootPath, [PathName], CancellationToken.None));
    }

    [Fact]
    public async Task ExactLocalProofRejectsDifferentImmutableProjectContext()
    {
        Fixture fixture = await CreateFixtureAsync(
            "public class Example { public int First() => 100; }",
            "public class Example { public int Other() => 100; }");
        fixture.Current.RepositoryPathSetIdentity = "different-project-context";
        Assert.Null(await RepositoryEvidenceIncrementalDeriver.TryDeriveAsync(fixture.Previous,
            fixture.Current, fixture.Current.RootPath, [PathName], CancellationToken.None));
    }

    [Fact]
    public void RawEvidenceEqualityDoesNotConflateInvalidUnicodeStrings()
    {
        EvidenceFact left = new()
        {
            Id = "fact",
            Kind = "kind",
            Scope = ".",
            Summary = "summary",
            Provenance = new()
            {
                SourceKind = EvidenceSourceKind.Observed,
                Analyzer = "analyzer",
                AnalyzerVersion = "version",
                Method = "method"
            },
            Locations = [new() { Path = "a.cs", Symbol = "\uD800" }],
        };
        Assert.False(RepositoryEvidenceValueEquality.Fact(left,
            left with { Locations = [new() { Path = "a.cs", Symbol = "\uFFFD" }] }));
        Assert.True(RepositoryEvidenceValueEquality.Fact(left,
            left with { Locations = [new() { Path = "a.cs", Symbol = "\uD800" }] }));
    }
}
