using EffortHours.Analysis;
using EffortHours.Analyzers.Terraform;
using EffortHours.Contracts;
using EffortHours.Contracts.V1;
using EffortHours.Core;

namespace EffortHours.Tests;

public sealed class TerraformAnalyzerSafetyTests
{
    private const string Analyzer = "efforthours.terraform-analyzer";

    [Fact]
    public async Task StatePlansLocksCachesAndGeneratedModulesAreNotAnalyzed()
    {
        InMemoryRepository repository = new();
        repository.WriteText("main.tf", "resource \"aws_s3_bucket\" \"kept\" {}\n");
        repository.WriteText("terraform.tfstate", "{\"resources\":[{\"secret\":\"state-secret\"}]}");
        repository.WriteText("saved.tfplan", "plan-secret");
        repository.WriteText(".terraform.lock.hcl", "provider \"registry.example/secret\" {}\n");
        repository.WriteText(".terraform/modules/vendor/main.tf", "resource \"aws_s3_bucket\" \"cached\" {}\n");
        repository.WriteText("generated/main.tf", "# <auto-generated>\nresource \"aws_s3_bucket\" \"generated\" {}\n");

        RepositoryEvidence evidence = await ScanAsync(repository);
        string json = ContractJson.Serialize(evidence);

        Assert.DoesNotContain(evidence.Facts, fact => fact.Kind == EvidenceKinds.TerraformArtifact &&
            fact.Locations.Any(location => location.Path is
                "terraform.tfstate" or "saved.tfplan" or ".terraform.lock.hcl" or
                ".terraform/modules/vendor/main.tf" or "generated/main.tf"));
        Assert.Contains(evidence.Facts, fact => fact.Kind == EvidenceKinds.ExcludedContent);
        Assert.DoesNotContain("state-secret", json, StringComparison.Ordinal);
        Assert.DoesNotContain("plan-secret", json, StringComparison.Ordinal);
        Assert.DoesNotContain("registry.example/secret", json, StringComparison.Ordinal);
    }

    [Fact]
    public async Task CredentialValuesAndSourceExcerptsAreNeverEmitted()
    {
        InMemoryRepository repository = new();
        repository.WriteText(
            "secrets.tfvars",
            "api_token = \"do-not-emit-this-value\"\nprivate_key = \"do-not-emit-this-key\"\n");

        RepositoryEvidence evidence = await ScanAsync(repository);
        string json = ContractJson.Serialize(evidence);

        Assert.Contains(evidence.Facts, fact => fact.Kind == EvidenceKinds.SecurityConfiguration &&
            fact.Provenance.Analyzer == Analyzer);
        Assert.Contains(evidence.Diagnostics, diagnostic => diagnostic.Code == "FB8605");
        Assert.DoesNotContain("do-not-emit-this", json, StringComparison.Ordinal);
        Assert.DoesNotContain("private_key =", json, StringComparison.Ordinal);
    }

    [Fact]
    public async Task TerraformJsonIsInventoryOnlyAndExplicitlyDiagnosed()
    {
        InMemoryRepository repository = new();
        repository.WriteText("main.tf.json", "{\"resource\":{\"aws_s3_bucket\":{\"x\":{}}}}");

        RepositoryEvidence evidence = await ScanAsync(repository);
        EvidenceFact language = Assert.Single(evidence.Facts, fact =>
            fact.Kind == EvidenceKinds.Language &&
            fact.Tags.Contains("language:terraform-json", StringComparer.Ordinal));

        Assert.Contains("analysis-status:inventory-only", language.Tags);
        Assert.Contains(evidence.Diagnostics, diagnostic => diagnostic.Code == "FB2002" &&
            diagnostic.Message.Contains("terraform-json", StringComparison.Ordinal));
        Assert.DoesNotContain(evidence.Facts, fact => fact.Provenance.Analyzer == Analyzer &&
            fact.Kind == EvidenceKinds.TerraformArtifact);
    }

    [Fact]
    public async Task DigestChangesAfterScanningAreRejected()
    {
        InMemoryRepository repository = new();
        repository.WriteText("main.tf", "resource \"aws_s3_bucket\" \"before\" {}\n");
        RepositoryEvidence common = await new EffortHours.Analysis.RepositoryScanner(repository)
            .ScanAsync(repository.RootPath);
        repository.WriteText("main.tf", "resource \"aws_s3_bucket\" \"after\" {}\n");

        RepositoryAnalysisContribution contribution = await new TerraformRepositoryAnalyzer(repository)
            .AnalyzeAsync(repository.RootPath, common);

        Assert.Contains(contribution.Diagnostics, diagnostic => diagnostic.Code == "FB8601" &&
            diagnostic.Message.Contains("changed after common scanning", StringComparison.Ordinal));
        Assert.DoesNotContain(contribution.Facts, fact => fact.Kind == EvidenceKinds.TerraformArtifact);
    }

    [Fact]
    public async Task UnreadableCanonicalCopyDoesNotSuppressReadableDuplicate()
    {
        const string source = "resource \"benchmark\" \"kept\" {}\n";
        InMemoryRepository repository = new();
        repository.WriteText("a.tf", source);
        repository.WriteText("b.tf", source);
        RepositoryEvidence common = await new RepositoryScanner(repository)
            .ScanAsync(repository.RootPath);
        repository.WriteText("a.tf", "changed after scan\n");

        RepositoryAnalysisContribution contribution = await new TerraformRepositoryAnalyzer(repository)
            .AnalyzeAsync(repository.RootPath, common);

        Assert.Contains(contribution.Diagnostics, diagnostic => diagnostic.Code == "FB8601");
        Assert.Contains(contribution.Facts, fact => fact.Kind == EvidenceKinds.TerraformArtifact &&
            fact.Locations.Any(location => location.Path == "b.tf") &&
            !fact.Tags.Contains("normalization:exact-content-duplicate", StringComparer.Ordinal));
        Assert.Contains(contribution.Facts, fact => fact.Kind == EvidenceKinds.Infrastructure);
    }

    [Fact]
    public void TokenAndSyntaxSafeguardsFailWithLowConfidence()
    {
        string oversized = string.Join(' ', Enumerable.Repeat("identifier", HclTokenizer.MaximumTokens + 1));

        HclDocumentAnalysis analysis = HclSyntaxAnalyzer.Analyze(oversized);
        HclDocumentAnalysis incomplete = HclSyntaxAnalyzer.Analyze("resource \"x\" \"y\" {\n");

        Assert.True(analysis.Truncated);
        Assert.Equal("low", analysis.ParserConfidence);
        Assert.False(incomplete.StructurallyBalanced);
        Assert.Equal("low", incomplete.ParserConfidence);
    }

    private static Task<RepositoryEvidence> ScanAsync(InMemoryRepository repository) =>
        new RepositoryAnalysisPipeline(repository).ScanAsync(repository.RootPath);
}
