namespace EffortHours.Analysis;

internal static class GeneratedFileClassification
{
    public static bool IsGeneratedPath(
        string lowerPath,
        string lowerName,
        string? language,
        string sampleText)
    {
        if (HasAnySegment(lowerPath, "generated", "gen") ||
            lowerName.EndsWith(".g.cs", StringComparison.Ordinal) ||
            lowerName.Contains(".generated.", StringComparison.Ordinal) ||
            lowerName.EndsWith(".designer.cs", StringComparison.Ordinal) ||
            lowerName.EndsWith(".assemblyattributes.cs", StringComparison.Ordinal))
        {
            return true;
        }

        if (IsSqlDump(lowerPath, lowerName, language, sampleText))
        {
            return true;
        }

        if (TerraformFileClassification.IsStateOrPlan(lowerName, Path.GetExtension(lowerName)))
        {
            return true;
        }

        if (ScriptingFileClassification.IsExcludedMaintainedBody(
            lowerPath,
            lowerName,
            language,
            sampleText))
        {
            return true;
        }

        if (language == "php" && PhpFileClassification.IsGeneratedPath(lowerPath)) return true;

        // Notebook outputs and attachments are excluded payloads and must not be
        // allowed to classify the maintained notebook body as generated. Path-
        // based generated conventions above remain authoritative for notebooks.
        if (language == "jupyter") return false;

        return sampleText.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase) ||
               sampleText.Contains("@generated", StringComparison.OrdinalIgnoreCase) ||
               sampleText.Contains("do not edit", StringComparison.OrdinalIgnoreCase) ||
               sampleText.Contains("generated by", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsSqlDump(
        string lowerPath,
        string lowerName,
        string? language,
        string sampleText)
    {
        if (language != "sql")
        {
            return false;
        }

        bool explicitlyMaintainedData = HasAnySegment(
            lowerPath,
            "seed",
            "seeds",
            "fixture",
            "fixtures",
            "test-data",
            "testdata");
        if (!explicitlyMaintainedData &&
            (HasAnySegment(lowerPath, "dump", "dumps", "backup", "backups", "snapshot", "snapshots", "export", "exports") ||
             lowerName.EndsWith(".dump.sql", StringComparison.Ordinal) ||
             lowerName.EndsWith(".bak.sql", StringComparison.Ordinal) ||
             lowerName.EndsWith(".snapshot.sql", StringComparison.Ordinal)))
        {
            return true;
        }

        string sample = sampleText.ToLowerInvariant();
        if (sample.Contains("postgresql database dump", StringComparison.Ordinal) ||
            sample.Contains("mysql dump", StringComparison.Ordinal) ||
            sample.Contains("dumped from database version", StringComparison.Ordinal) ||
            sample.Contains(" from stdin;", StringComparison.Ordinal) &&
            sample.Contains("copy ", StringComparison.Ordinal))
        {
            return true;
        }

        return !explicitlyMaintainedData && CountOccurrences(sample, "insert into ", 40) >= 40;
    }

    private static int CountOccurrences(string value, string candidate, int limit)
    {
        int count = 0;
        int offset = 0;
        while (count < limit)
        {
            int index = value.IndexOf(candidate, offset, StringComparison.Ordinal);
            if (index < 0)
            {
                break;
            }

            count++;
            offset = index + candidate.Length;
        }

        return count;
    }

    private static bool HasAnySegment(string lowerPath, params string[] candidates)
    {
        string[] segments = lowerPath.Split('/', StringSplitOptions.RemoveEmptyEntries);
        return segments.Any(segment => candidates.Contains(segment, StringComparer.Ordinal));
    }
}
