namespace EffortHours.Analysis;

internal static class ScriptingFileClassification
{
    private static readonly HashSet<string> ShellExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".sh", ".bash", ".ksh", ".bats",
    };

    private static readonly HashSet<string> PowerShellExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".ps1", ".psm1", ".psd1",
    };

    private static readonly HashSet<string> ShellProfileNames = new(StringComparer.OrdinalIgnoreCase)
    {
        ".profile", ".bash_profile", ".bash_login", ".bashrc",
    };

    private static readonly HashSet<string> CopiedLauncherNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "gradlew", "mvnw", "dotnet-install.sh", "install-powershell.ps1",
    };

    public static string? DetectLanguage(
        string lowerName,
        string extension,
        string sampleText)
    {
        if (ShellExtensions.Contains(extension) || ShellProfileNames.Contains(lowerName))
        {
            return "shell";
        }

        if (PowerShellExtensions.Contains(extension))
        {
            return "powershell";
        }

        if (extension.Length > 0 && extension != ".command")
        {
            return null;
        }

        string firstLine = FirstLine(sampleText).TrimStart('\uFEFF').Trim();
        if (!firstLine.StartsWith("#!", StringComparison.Ordinal))
        {
            return null;
        }

        string shebang = firstLine[2..].Trim().ToLowerInvariant();
        if (HasInterpreter(shebang, "pwsh") || HasInterpreter(shebang, "powershell"))
        {
            return "powershell";
        }

        return HasInterpreter(shebang, "sh") ||
            HasInterpreter(shebang, "ash") ||
            HasInterpreter(shebang, "bash") ||
            HasInterpreter(shebang, "dash") ||
            HasInterpreter(shebang, "ksh")
                ? "shell"
                : null;
    }

    public static bool IsTest(string lowerPath, string lowerName, string? language)
    {
        if (language is not ("shell" or "powershell"))
        {
            return false;
        }

        if (Path.GetExtension(lowerName).Equals(".bats", StringComparison.Ordinal))
        {
            return true;
        }

        string stem = ScriptStem(lowerName);
        return HasAnySegment(lowerPath, "test", "tests", "spec", "specs", "smoke") ||
            stem.StartsWith("test-", StringComparison.Ordinal) ||
            stem.StartsWith("test_", StringComparison.Ordinal) ||
            stem.EndsWith("-test", StringComparison.Ordinal) ||
            stem.EndsWith("_test", StringComparison.Ordinal) ||
            stem.EndsWith(".test", StringComparison.Ordinal) ||
            stem.EndsWith(".tests", StringComparison.Ordinal) ||
            stem.EndsWith(".spec", StringComparison.Ordinal);
    }

    public static bool IsExcludedMaintainedBody(
        string lowerPath,
        string lowerName,
        string? language,
        string sampleText)
    {
        if (language is not ("shell" or "powershell"))
        {
            return false;
        }

        if (CopiedLauncherNames.Contains(lowerName) || IsCompletion(lowerPath, lowerName))
        {
            return true;
        }

        string sample = sampleText.ToLowerInvariant();
        return sample.Contains("generated completion", StringComparison.Ordinal) ||
            sample.Contains("this file was generated by", StringComparison.Ordinal) ||
            sample.Contains("do not edit this generated", StringComparison.Ordinal);
    }

    public static bool IsCiAutomation(string lowerPath, string lowerName, string? language) =>
        IsScript(language) &&
        (HasAnySegment(lowerPath, ".ci", "ci", "pipeline", "pipelines") ||
         ScriptStem(lowerName) is "ci" or "pipeline");

    public static bool IsBuildAutomation(string lowerPath, string lowerName, string? language)
    {
        if (!IsScript(language))
        {
            return false;
        }

        if (language == "powershell" && Path.GetExtension(lowerName) == ".psd1")
        {
            return true;
        }

        if (ShellProfileNames.Contains(lowerName) ||
            HasAnySegment(lowerPath, "build", "eng", "tooling"))
        {
            return true;
        }

        return ScriptStem(lowerName) is
            "build" or "bootstrap" or "clean" or "configure" or "format" or
            "generate" or "lint" or "restore" or "setup";
    }

    public static bool IsDeliveryAutomation(string lowerPath, string lowerName, string? language)
    {
        if (!IsScript(language))
        {
            return false;
        }

        if (HasAnySegment(lowerPath, "release", "releases", "packaging"))
        {
            return true;
        }

        return ScriptStem(lowerName) is
            "install" or "package" or "pack" or "publish" or "release" or "uninstall";
    }

    public static bool IsInfrastructureAutomation(
        string lowerPath,
        string lowerName,
        string? language)
    {
        if (!IsScript(language))
        {
            return false;
        }

        if (HasAnySegment(lowerPath, "deploy", "deployment", "devops", "ops", "provision"))
        {
            return true;
        }

        return ScriptStem(lowerName) is "deploy" or "provision" or "rollback" or "teardown";
    }

    private static bool IsCompletion(string lowerPath, string lowerName)
    {
        if (HasAnySegment(
            lowerPath,
            "completion",
            "completions",
            "bash-completion",
            "bash_completion.d",
            "shell-completion"))
        {
            return true;
        }

        return lowerName.EndsWith(".completion.sh", StringComparison.Ordinal) ||
            lowerName.EndsWith("-completion.sh", StringComparison.Ordinal) ||
            lowerName.EndsWith("_completion.sh", StringComparison.Ordinal) ||
            lowerName.EndsWith(".bash-completion", StringComparison.Ordinal);
    }

    private static string ScriptStem(string lowerName)
    {
        string extension = Path.GetExtension(lowerName);
        return ShellExtensions.Contains(extension) || PowerShellExtensions.Contains(extension)
            ? lowerName[..^extension.Length]
            : lowerName;
    }

    private static bool HasInterpreter(string shebang, string interpreter)
    {
        string[] parts = shebang.Split(
            [' ', '\t'],
            StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return parts.Any(part =>
            Path.GetFileName(part).Equals(interpreter, StringComparison.Ordinal) ||
            part.Equals(interpreter, StringComparison.Ordinal));
    }

    private static string FirstLine(string value)
    {
        int newline = value.IndexOfAny(['\r', '\n']);
        return newline < 0 ? value : value[..newline];
    }

    private static bool IsScript(string? language) => language is "shell" or "powershell";

    private static bool HasAnySegment(string lowerPath, params string[] candidates)
    {
        string[] segments = lowerPath.Split('/', StringSplitOptions.RemoveEmptyEntries);
        return segments.Any(segment => candidates.Contains(segment, StringComparer.Ordinal));
    }
}
