<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClCompile Include="status_windows.cpp" />
  </ItemGroup>
  <PropertyGroup>
    <ConfigurationType>StaticLibrary</ConfigurationType>
    <LanguageStandard>stdcpp20</LanguageStandard>
  </PropertyGroup>
</Project>
